const TASK_STATUS = {
  TODO_WAIT: 'TODO_WAIT',
  TODO_SUCCESS: 'TODO_SUCCESS',
  TODO_FAIL: 'TODO_FAIL',
  TODO_SOME_SUCCESS: 'TODO_SOME_SUCCESS',
  DOWITH_WAIT: 'DOWITH_WAIT',
  DOWITH_SUCCESS: 'DOWITH_SUCCESS',
  DOWITH_FAIL: 'DOWITH_FAIL',
  DOWITH_SOME_SUCCESS: 'DOWITH_SOME_SUCCESS',
  ALL_WAIT: 'ALL_WAIT',
  ALL_SUCCESS: 'ALL_SUCCESS',
  ALL_FAIL: 'ALL_FAIL',
  ALL_SOME_SUCCESS: 'ALL_SOME_SUCCESS',
  NONE: 'NONE',
} as const;

export { TASK_STATUS };
