const TASK_STATUS = {
  TODO_WAIT: 'TODO_WAIT',
  TODO_SUCCESS: 'TODO_SUCCESS',
  TODO_FAIL: 'TODO_FAIL',
  ONLY_TODO_SUCCESS: 'ONLY_TODO_SUCCESS',
  DOWITH_WAIT: 'DOWITH_WAIT',
  DOWITH_SUCCESS: 'DOWITH_SUCCESS',
  DOWITH_FAIL: 'DOWITH_FAIL',
  ONLY_DOWITH_SUCCESS: 'ONLY_DOWITH_SUCCESS',
  ALL_WAIT: 'ALL_WAIT',
  ALL_SUCCESS: 'ALL_SUCCESS',
  ALL_FAIL: 'ALL_FAIL',
  NONE: 'NONE',
} as const;

export { TASK_STATUS };
