import { z } from 'zod';

const CREATION_TYPE_ENUM = z.enum(['COMMON', 'USER_CUSTOM']);
const TASK_STATUS_ENUM = z.enum(['WAIT', 'SUCCESS', 'FAIL']);
const DOWITH_TASK_STATUS_ENUM = z.enum(['WAIT', 'IN_PROGRESS', 'COMPLETE']);
const TASK_ROUTINE_CYCLE_ENUM = z.enum(['DAILY', 'WEEKLY', 'MONTHLY']);

export { CREATION_TYPE_ENUM, TASK_STATUS_ENUM, DOWITH_TASK_STATUS_ENUM, TASK_ROUTINE_CYCLE_ENUM };
